# Generated by Django 5.2 on 2025-04-16 17:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100, verbose_name='Заголовок страницы')),
                ('page_text', ckeditor.fields.RichTextField(verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Инфо страница',
                'verbose_name_plural': 'Инфо страницы',
            },
        ),
    ]
