# Generated by Django 5.2 on 2025-04-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_category_subcategory_subsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=50, verbose_name='Зголовок опции')),
            ],
            options={
                'verbose_name': 'Опция категории',
                'verbose_name_plural': 'Опции категории',
            },
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'verbose_name': 'Под-подкатегория', 'verbose_name_plural': 'Под-подкатегории'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image', verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(max_length=50, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subsub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image', verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subsub_category_name',
            field=models.CharField(max_length=50, verbose_name='Название под-подкатегории'),
        ),
        migrations.CreateModel(
            name='CategoryOptionsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_field', models.CharField(max_length=50, verbose_name='Поле опции')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_option', to='items.categoryoptions', verbose_name='Опция')),
            ],
        ),
    ]
