# Generated by Django 5.2 on 2025-04-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_categoryoptions_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoptionsfields',
            options={'verbose_name': 'Поля категории', 'verbose_name_plural': 'Поля категории'},
        ),
        migrations.AddField(
            model_name='categoryoptions',
            name='subsub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='items.subsubcategory', verbose_name='под-подкатегории'),
            preserve_default=False,
        ),
    ]
