# Generated by Django 5.2 on 2025-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_categoryoptionsfields_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoptions',
            name='self_completion',
            field=models.BooleanField(default=False),
        ),
    ]
