# Generated by Django 5.2 on 2025-04-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_categoryoptions_self_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_image', models.ImageField(upload_to='announcement_image', verbose_name='Картинка обьявления')),
                ('description', models.TextField(max_length=6000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('hide_phone', models.BooleanField(default=False, verbose_name='Скрыть номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_fields', models.JSONField(default=dict, verbose_name='Поля опций')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.subsubcategory', verbose_name='Категория')),
            ],
        ),
    ]
