# Generated by Django 5.2 on 2025-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.IntegerField(verbose_name='Id категории'),
        ),
    ]
