# Generated by Django 5.2 on 2025-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_rename_isting_image_listing_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(upload_to='listing_image', verbose_name='Картника объявления'),
        ),
    ]
