# Generated by Django 5.2 on 2025-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_listing_listing_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='listing',
            name='past_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Прошлая цена'),
        ),
    ]
