# Generated by Django 5.2 on 2025-04-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_listing_options_listing_past_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='listening_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь объявления'),
            preserve_default=False,
        ),
    ]
