# Generated by Django 5.2 on 2025-04-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_listinginfo_emailaddress_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='listing_info',
        ),
        migrations.RemoveField(
            model_name='address',
            name='listing_info',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='listing_info',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='listing_info',
        ),
        migrations.AddField(
            model_name='address',
            name='listing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='items.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='items.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='items.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='listing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='social_network', to='items.listing'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ListingInfo',
        ),
    ]
