# Generated by Django 5.2 on 2025-04-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_remove_emailaddress_listing_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=600, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Понедельник')),
                ('tuesday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Вторник')),
                ('wednesday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Среда')),
                ('thursday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Четверг')),
                ('friday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Пятница')),
                ('saturday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Суббота')),
                ('sunday', models.CharField(default='Круглосуточно', max_length=30, verbose_name='Воскресенье')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='items.listing')),
            ],
            options={
                'verbose_name': 'Дни работы',
            },
        ),
    ]
