# Generated by Django 5.2 on 2025-05-04 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_phonenumber_number_workdays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdays',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='address',
            name='listing',
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='ad_image', verbose_name='Картника объявления')),
                ('description', models.TextField(max_length=6000, verbose_name='Описание')),
                ('category', models.IntegerField(verbose_name='Id категории')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('past_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Прошлая цена')),
                ('currency', models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('hide_phone', models.BooleanField(default=False, verbose_name='Скрыть номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_fields', models.JSONField(default=dict, verbose_name='Поля опций')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='address',
            name='Ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='items.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='Ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='items.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorit',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='items.ad', verbose_name='Объявление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='Ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='items.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='Ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_network', to='items.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workdays',
            name='Ad',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='items.ad'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorit',
            unique_together={('user', 'ad')},
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
