# Generated by Django 5.2 on 2025-05-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_remove_workdays_listing_remove_socialnetwork_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='Ad',
            new_name='ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='ad_image',
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad_images')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.ad')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявления',
            },
        ),
    ]
