# Generated by Django 5.2 on 2025-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_rename_ad_phonenumber_ad_remove_ad_ad_image_adimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Показы'),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
