# Generated by Django 5.2 on 2025-05-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_ad_impressions_ad_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category', verbose_name='Id категории'),
        ),
    ]
