# Generated by Django 5.2 on 2025-05-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_ad_update_at_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.IntegerField(verbose_name='Id категории (временно)'),
        ),
    ]
