# Generated by Django 5.2 on 2025-05-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_ad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='СategoryAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок рекламы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_advertising', to='items.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_advertising', to='items.subcategory')),
                ('subsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories_advertising', to='items.subsubcategory')),
            ],
            options={
                'verbose_name': 'Рекламы категории',
            },
        ),
    ]
