# Generated by Django 5.2 on 2025-05-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_сategoryadvertising'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сategoryadvertising',
            options={'verbose_name': 'Реклама категории', 'verbose_name_plural': 'Рекламы категорий'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.subsubcategory', verbose_name='Id категории'),
        ),
    ]
