# Generated by Django 5.2 on 2025-05-11 19:37

import apps.items.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_сategoryadvertising_options_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to=apps.items.utils.directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to=apps.items.utils.directory_path, verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.items.utils.directory_path, verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subsub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.items.utils.directory_path, verbose_name='Картинка категории'),
        ),
    ]
