# Generated by Django 5.2 on 2025-05-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_alter_adimage_image_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
