# Generated by Django 5.2 on 2025-05-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_adimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adimage',
            name='is_main',
        ),
    ]
