# Generated by Django 5.2 on 2025-05-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_remove_adimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoptions',
            name='option_title',
            field=models.CharField(max_length=50, verbose_name='Заголовок опции'),
        ),
        migrations.CreateModel(
            name='AdMapСoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='items.ad')),
            ],
            options={
                'verbose_name': 'Координаты карты объявления',
                'verbose_name_plural': 'Координаты карты объявления',
            },
        ),
    ]
