# Generated by Django 5.2 on 2025-05-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_alter_categoryoptions_option_title_admapсoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
