# Generated by Django 5.2 on 2025-05-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_ad_is_deactivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='option_fields',
        ),
        migrations.CreateModel(
            name='AdCategoryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_self_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Самозаполнение')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_options', to='items.ad', verbose_name='Объявление')),
                ('option_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_option_fields', to='items.categoryoptionsfields')),
                ('option_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_option_titles', to='items.categoryoptions')),
            ],
            options={
                'verbose_name': 'Опция объявления',
                'verbose_name_plural': 'Опции объявлений',
            },
        ),
    ]
