# Generated by Django 5.2 on 2025-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_remove_ad_option_fields_adcategoryoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='option_fields',
            field=models.JSONField(default=dict, verbose_name='Поля опций'),
        ),
    ]
