# Generated by Django 5.2 on 2025-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_ad_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='option_fields',
        ),
        migrations.RemoveField(
            model_name='adcategoryoptions',
            name='option_self_text',
        ),
        migrations.AddField(
            model_name='adcategoryoptions',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Значение опции'),
        ),
    ]
