# Generated by Django 5.2 on 2025-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_remove_ad_option_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='option_fields',
            field=models.JSONField(default=dict, verbose_name='Поля опций'),
        ),
        migrations.DeleteModel(
            name='AdCategoryOptions',
        ),
    ]
