# Generated by Django 5.2 on 2025-06-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_ad_option_fields_delete_adcategoryoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.categoryoptions', verbose_name='Опция категории'),
        ),
    ]
