# Generated by Django 5.2 on 2025-06-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_remove_ad_option_ad_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='options',
        ),
    ]
