# Generated by Django 5.2 on 2025-06-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_remove_ad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='field text')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fielsd', to='items.ad')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='items.categoryoptionsfields')),
            ],
            options={
                'verbose_name': 'Поле категории',
                'verbose_name_plural': 'Поля категорий',
            },
        ),
    ]
