# Generated by Django 5.2 on 2025-06-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_chosenfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='option_fields',
        ),
        migrations.AddField(
            model_name='chosenfields',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='items.categoryoptions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chosenfields',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='items.ad'),
        ),
        migrations.AlterField(
            model_name='chosenfields',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='items.categoryoptionsfields'),
        ),
        migrations.AlterField(
            model_name='chosenfields',
            name='value',
            field=models.CharField(max_length=50, null=True, verbose_name='value'),
        ),
    ]
