# Generated by Django 5.2 on 2025-06-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_remove_ad_option_fields_chosenfields_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosenfields',
            options={'verbose_name': 'Выбранное поле', 'verbose_name_plural': 'ыбранные поля'},
        ),
    ]
