# Generated by Django 5.2 on 2025-06-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0041_alter_chosenfields_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosenfields',
            options={'verbose_name': 'Выбранное поле', 'verbose_name_plural': 'Выбранные поля'},
        ),
        migrations.RemoveField(
            model_name='chosenfields',
            name='ad',
        ),
        migrations.CreateModel(
            name='AdCategoryFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to=settings.AUTH_USER_MODEL, verbose_name='category_fields')),
            ],
            options={
                'verbose_name': 'Поля категорий объявления',
                'verbose_name_plural': 'Поля категорий объявления',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category_options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.adcategoryfields', verbose_name='Поля категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chosenfields',
            name='ad_category_fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ad_categoy_fields', to='items.adcategoryfields', verbose_name='ad_categoy_fields'),
            preserve_default=False,
        ),
    ]
