# Generated by Django 5.2 on 2025-06-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0042_alter_chosenfields_options_remove_chosenfields_ad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chosenfields',
            old_name='ad_category_fields',
            new_name='ad_categoy_fields',
        ),
    ]
