# Generated by Django 5.2 on 2025-06-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0043_rename_ad_category_fields_chosenfields_ad_categoy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcategoryfields',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.subsubcategory', verbose_name='Id категории'),
            preserve_default=False,
        ),
    ]
