# Generated by Django 5.2 on 2025-06-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0044_adcategoryfields_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosenfields',
            name='value',
        ),
    ]
