# Generated by Django 5.2 on 2025-06-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0045_remove_chosenfields_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Ad',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='Ad',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='workdays',
            old_name='Ad',
            new_name='ad',
        ),
    ]
