# Generated by Django 5.2 on 2025-06-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0046_rename_ad_address_ad_rename_ad_emailaddress_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='social_network_name',
        ),
    ]
