# Generated by Django 5.2 on 2025-06-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0047_remove_socialnetwork_social_network_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='Ad',
            new_name='ad',
        ),
    ]
