# Generated by Django 5.2 on 2025-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_usernickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usernickname',
            field=models.CharField(max_length=50, null=True, verbose_name='логин'),
        ),
    ]
