# Generated by Django 5.2 on 2025-05-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_usernickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_user',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован через Google'),
        ),
    ]
