# Generated by Django 5.2 on 2025-05-11 19:37

import apps.items.utils
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_is_google_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание пользователя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.items.utils.directory_path, verbose_name='Изображение пользователя'),
        ),
    ]
