# Generated by Django 5.2 on 2025-04-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisment_image', models.ImageField(upload_to='advertisment', verbose_name='Реклама')),
                ('advertisment_url', models.URLField(verbose_name='Ссылка рекламы')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FooterCopyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=50, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Копирайт',
            },
        ),
        migrations.CreateModel(
            name='FooterSiteLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_link_text', models.CharField(max_length=20, verbose_name='Текст ссылка в футере')),
                ('footer_link_url', models.URLField(verbose_name='Ссылка текста в футере')),
                ('is_social', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
            },
        ),
        migrations.CreateModel(
            name='FooterSiteLinksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_category', models.CharField(max_length=20, verbose_name='Категория футера')),
            ],
            options={
                'verbose_name': 'Категория футера',
                'verbose_name_plural': 'Категории футера',
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='header_site', verbose_name='Лого сайта')),
            ],
            options={
                'verbose_name': 'Лого сайта',
                'verbose_name_plural': 'Логи сайта',
            },
        ),
        migrations.DeleteModel(
            name='HeaderLogo',
        ),
        migrations.AlterModelOptions(
            name='burgercategory',
            options={'verbose_name': 'Категория бургера', 'verbose_name_plural': 'Категории бургера'},
        ),
        migrations.AddField(
            model_name='burgerlinks',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burgercategory',
            name='category_text',
            field=models.CharField(max_length=30, verbose_name='Текст бургер категории'),
        ),
        migrations.AlterField(
            model_name='burgerlinks',
            name='url_link',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='footersitelinks',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='core.footersitelinkscategory'),
        ),
    ]
