# Generated by Django 5.2 on 2025-05-11 19:37

import apps.items.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_burgerlinks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisments',
            name='advertisment_image',
            field=models.ImageField(upload_to=apps.items.utils.directory_path, verbose_name='Реклама'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='header_logo',
            field=models.ImageField(upload_to=apps.items.utils.directory_path, verbose_name='Лого сайта'),
        ),
    ]
