# Generated by Django 5.2 on 2025-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_advertisments_advertisment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgercategory',
            name='category_link',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
    ]
