# Generated by Django 5.2 on 2025-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_burgercategory_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgercategory',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
    ]
