# Generated by Django 5.2 on 2025-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_burgercategory_is_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burgercategory',
            old_name='is_social',
            new_name='is_facebook',
        ),
        migrations.AddField(
            model_name='burgercategory',
            name='is_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='burgercategory',
            name='is_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
